name: pfas_website
channels:
  - conda-forge
dependencies:
  - python=3.10.12
  - numpy=1.23.5
  - pandas=2.0.3
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - scikit-learn=1.2.2
  - catboost=1.2.1
  - imbalanced-learn=0.11.0
  - streamlit=1.35.0